### ISSUE TITLE
What about a standard badge for package README files ?

### ISSUE THREAD

**Issue by j-fu** [fredrikekre/Runic.jl#108]
May be this ?

[![Runic Formatted](https://img.shields.io/badge/Formatted_by-%E1%9A%B1%E1%9A%A2%E1%9A%BE%E1%9B%81%E1%9A%B2-black)](https://github.com/fredrikekre/Runic.jl)

**Comment by fredrikekre** [comment]
I was a bit skeptical of this when reading the issue title but it is kinda funny that you can use unicode in the label.

It seems that it is convention to use `code style` for this (see e.g. https://github.com/psf/black?tab=readme-ov-file#show-your-style and https://github.com/prettier/prettier?tab=readme-ov-file#badge) so perhaps this:

[![Runic Formatted](https://img.shields.io/badge/code_style-%E1%9A%B1%E1%9A%A2%E1%9A%BE%E1%9B%81%E1%9A%B2-black)](https://github.com/fredrikekre/Runic.jl)

Some other more cryptic but nice looking alternatives:
[![Runic Formatted](https://img.shields.io/badge/%E1%9A%B1%E1%9A%A2%E1%9A%BE%E1%9B%81%E1%9A%B2-black)](https://github.com/fredrikekre/Runic.jl)
[![Runic Formatted](https://img.shields.io/badge/%E1%9A%B1%E1%9A%A2%E1%9A%BE%E1%9B%81%E1%9A%B2-grey)](https://github.com/fredrikekre/Runic.jl)

**Comment by j-fu** [comment]
Yeah didn't know this either, thought to create some image, just got the idea to try. 

I think the "code style" version would be the way to go. And of course it is yours to decide, including the colors...

**Comment by fredrikekre** [comment]
Thanks for the idea and suggestion, I think it looks cool :)
