### ISSUE TITLE
Syntax for formatting individual file is annoying

### ISSUE THREAD

**Issue by araujoms** [fredrikekre/Runic.jl#126]
If I just want to run `Runic` on the file `test.jl`, I need to do
```julia
using Runic
Runic.format_file("test.jl"; inplace = true)
```
For comparison, with JuliaFormatter I only need to do
```julia
using JuliaFormatter
format("test.jl")
```
Just export the function and let the default value for `inplace` be `true`.

**Comment by fredrikekre** [comment]
Since it is a (potentially) destructive operation I like the explicitness of requiring the `inplace` keyword argument. I also prefer not exporting names, but they can be marked with `public` in supported Julia versions (see #127).
