### ISSUE TITLE
Runic adds double line spacing

### ISSUE THREAD

**Issue by KnutAM** [fredrikekre/Runic.jl#18]
Nice package! 

I'm quite happy with the suggestions from Runic.jl [here](https://github.com/Ferrite-FEM/FerriteMeshParser.jl/pull/50) (especially if #12 would be included).

But for some reason double line spacing is added in [`docs/make.jl`](https://github.com/Ferrite-FEM/FerriteMeshParser.jl/pull/50/files#diff-4aae2d1c783cade58bd2cb13748da956e568b7f2aed5fafd9e2a46fb97daf613)

E.g. 
```diff
using FerriteMeshParser
using Documenter

+
const is_ci = get(ENV, "CI", "false") == "true"
```

Simply ran `julia -e 'using Pkg; Pkg.activate(;temp=true); Pkg.add(url = "https://github.com/fredrikekre/Runic.jl"); using Runic; exit(Runic.main(ARGS))' -- -i .`

(I tried changed all line endings from CRLF to LF, but cannot rule out that this could be an issue still somehow)

**Comment by fredrikekre** [comment]
Xref https://github.com/JuliaGeometry/DelaunayTriangulation.jl/pull/138#discussion_r1676791621 

Probably fixed by https://github.com/JuliaLang/JuliaSyntax.jl/pull/460 and most likely Windows related

**Comment by KnutAM** [comment]
> (I tried changed all line endings from CRLF to LF, but cannot rule out that this could be an issue still somehow

Apparently, this must have been the issue. Can reproduce the behavior only when making sure that `docs/make.jl` has CRLF line endings, with LF line endings, it works as intended.

I could not test with the proposed fixed, since I couldn't figure out the version compatibility with julia syntax since JuliaSyntax#main is v0.4.6 but Runic.jl requires the released v0.4.8. 

Here are minimum reproducers with lf and crlf in case helpful: [testfiles.zip](https://github.com/user-attachments/files/16279592/testfiles.zip)

**Comment by fredrikekre** [comment]
Try again with JuliaSyntax@0.4.9 and Runic master? Probably have to reset the commit first because Runic will not revert the double lines once they are in the source.

**Comment by KnutAM** [comment]
Can confirm that it works, ref https://github.com/Ferrite-FEM/FerriteMeshParser.jl/pull/51/files
