### ISSUE TITLE
After linebreaks following `=`, indentation is off

### ISSUE THREAD

**Issue by lmshk** [fredrikekre/Runic.jl#39]
For example, Runic reformats
```julia
y =
    if x
      1
    else
      2
    end
```
to
```julia
y =
    if x
    1
else
    2
end
```
which is likely not intended.

(This also applies to short-form function definitions with linebreaks after the `=`.)

**Comment by fredrikekre** [comment]
Given the existing rules I would have guessed the result would be
```
y = if x
        1
    else
        2
    end
```
but that doesn't look very good either. Probably proper blocks like `if-end` should have some more "inertia" for changes like this because code like
```
y = if x
    1
else
    2
end
```
is pretty common. The style you have with a line break before the `if` I haven't seen much actually. Would you expect
```
y =
if x
    1
else
    2
end
```
?

**Comment by lmshk** [comment]
I would expect my original form, because the expression as continued on the second line is just indented once. (I usually do this if `?`/`:` does not fit on the first line.)

I'd be fine with your first example as well. (If I write it like that, Runic leaves it as it is.)

**Comment by adienes** [comment]
I think it should be
```
y = if x
    1
else
    2
end
```

the other options present look off to me

**Comment by lmshk** [comment]
That implies that for long conditions, breaking the line then would indent the continuation at the same level as the body. (Similarly for short-form function definitions).

Also, my understanding is that Runic is supposed to leave linebreaks intact; if you prefer `y = if x`, you can already write it like that and it will not be broken up.
